name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Display version
        run: |
          python --version
          pip --version

      - name: Install pypa/build
        run: |
          pip install build

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build

      - name: Display content dist folder
        run: |
          ls -l dist/

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: dist

  test:
    name: Test Packaging
    needs: build
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/download-artifact@v3

      - name: Display content working folder
        run: |
          ls -R

      - name: Install HyperSpy (dev)
        run: |
          pip install https://github.com/hyperspy/hyperspy/archive/refs/heads/RELEASE_next_major.zip

      - name: Install distribution
        run: |
          pip install --pre --find-links dist holospy[tests]

      - name: Test distribution
        run: |
          pytest --pyargs holospy
