name: Release

# This workflow builds the wheels "on tag".
# If run from the hyperspy/hyperspy repository, the wheels will be uploaded to pypi ;
# otherwise, the wheels will be available as a github artifact.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release_and_upload:
    name: Release and Upload
    permissions:
      # needs write permission to create the GitHub release
      contents: write
      # This permission is mandatory for trusted publishing on pypi
      id-token: write
    # Use the "reusable workflow" from the hyperspy organisation
    uses: hyperspy/.github/.github/workflows/release_pure_python.yml@main
    with:
      repository_owner: 'hyperspy'
